Poprawka dla filtrowania po grupach
PepperTweaker/PepperTweaker pull request #8
Opened 2023-05-03 13:51 UTC by Igloczek

Najprawdopodobniej po zmianach po stronie Peppera, przestało działać filtrowania po grupach, ten PR je naprawia.

Problem leżał w tym, że w zwracanym HTML nie ma już wyrenderowanych breadcrumbsów, bo dzieje się to dopiero na kliencie, przez komponent Vue.js, wiec tablica z grupami danej oferty zawsze była pusta.

Problem rozwiązałem wyciągając dane z obiektu, który jest używany do hydracji komponentów renderujących UI na kliencie.

Kod jest mocno wypchany kapkę oczywistymi komentarzami, żeby się nie trzeba było za wiele domyślać, ale oczywiście mogę to wyrzucić, żeby stylem pasowało do reszty projektu.

2023-07-25 15:01 UTC, Igloczek commented
@bearbyt3z bedziesz cos z tym robił czy zamknac w cholere i nie zawracac dupy?

2023-07-26 02:19 UTC, bearbyt3z requested changes
@Igloczek Testowałem kod już wcześniej i wygląda w porządku. Dwie zmiany miałem wprowadzić, ale skoro jesteś aktywny, to wrzuciłem je jako "Request chamges".

2023-07-26 02:19 UTC, bearbyt3z commented on PepperTweaker.user.js
> +
Ten test jest niepotrzebny, bo realizuje go kolejny `if` sprawdzający wynik wyrażenia regularnego.

2023-07-26 02:19 UTC, bearbyt3z commented on PepperTweaker.user.js
> +              for (let scriptElement of scriptElements) {
Skoro `scriptElement` się nie zmienia, to lepsze będzie `const scriptElement`.

2023-07-27 02:28 UTC, merged